
package ws.services.Impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Tue Feb 18 11:24:35 GMT 2014
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "deleteTokenResponse", namespace = "http://Impl.services.ws/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteTokenResponse", namespace = "http://Impl.services.ws/")

public class DeleteTokenResponse {


}

