
package ws.services.Impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Tue Feb 18 11:23:22 GMT 2014
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "editEventById", namespace = "http://Impl.services.ws/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "editEventById", namespace = "http://Impl.services.ws/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5", "arg6", "arg7"})

public class EditEventById {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;
    @XmlElement(name = "arg3")
    private java.lang.String arg3;
    @XmlElement(name = "arg4")
    private java.util.Date arg4;
    @XmlElement(name = "arg5")
    private int arg5;
    @XmlElement(name = "arg6")
    private int arg6;
    @XmlElement(name = "arg7")
    private boolean arg7;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

    public java.lang.String getArg3() {
        return this.arg3;
    }

    public void setArg3(java.lang.String newArg3)  {
        this.arg3 = newArg3;
    }

    public java.util.Date getArg4() {
        return this.arg4;
    }

    public void setArg4(java.util.Date newArg4)  {
        this.arg4 = newArg4;
    }

    public int getArg5() {
        return this.arg5;
    }

    public void setArg5(int newArg5)  {
        this.arg5 = newArg5;
    }

    public int getArg6() {
        return this.arg6;
    }

    public void setArg6(int newArg6)  {
        this.arg6 = newArg6;
    }

    public boolean getArg7() {
        return this.arg7;
    }

    public void setArg7(boolean newArg7)  {
        this.arg7 = newArg7;
    }

}

