
package ws.services.Impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Tue Feb 18 11:23:47 GMT 2014
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "getEmployeesRegisteredForGradTrainingResponse", namespace = "http://Impl.services.ws/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeesRegisteredForGradTrainingResponse", namespace = "http://Impl.services.ws/")

public class GetEmployeesRegisteredForGradTrainingResponse {

    @XmlElement(name = "return")
    private java.util.List<ws.dao.Employee> _return;

    public java.util.List<ws.dao.Employee> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<ws.dao.Employee> new_return)  {
        this._return = new_return;
    }

}

